# -*- coding: utf-8 -*-
"""TPI_Gestion_Paises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XKLwMRRyRwe9MWO4pr4Eok8zaiNd8ck
"""

import csv

# Creacion del dataset base de países en formato CSV
contenido_csv = """nombre,poblacion,superficie,continente
Argentina,45376763,2780400,América
Brasil,213993437,8515767,América
Chile,19458310,756102,América
México,126014024,1964375,América
España,47415750,505990,Europa
Francia,67413000,643801,Europa
Alemania,83149300,357022,Europa
China,1412600000,9596960,Asia
India,1380004385,3287263,Asia
Japón,125800000,377975,Asia
Nigeria,206139589,923768,África
Egipto,102334404,1001449,África
Australia,25499884,7692024,Oceanía"""

# si el archivo no existe, lo crea
try:
    with open("paises.csv", "x", encoding="utf-8") as f:
        f.write(contenido_csv)
    print("Archivo paises.csv creado correctamente.")
except FileExistsError:
    pass

# variables globales
ARCHIVO_CSV = "paises.csv"
CAMPOS = ["nombre", "poblacion", "superficie", "continente"]
CONTINENTES = ["Asia", "América", "Europa", "África", "Oceanía"]

"""Lee el archivo CSV y retorna una lista de diccionarios.
Si el archivo no existe retorna una lista vacía. """
def cargar_paises():
    # Lista vacía que se irá llenando con los datos del CSV
    paises = []
    try:
        # Abre el archivo CSV en modo lectura con codificación utf-8
        # (utf-8 es necesario para que lea correctamente tildes y caracteres especiales)
        # newline='' evita que Python agregue saltos de línea extra al leer
        with open(ARCHIVO_CSV, newline='', encoding='utf-8') as f:

            # DictReader lee el CSV y convierte cada fila en un diccionario,
            # usando la primera fila (encabezado) como claves.
            # Ejemplo: {"nombre": "Argentina", "poblacion": "45376763", ...}
            reader = csv.DictReader(f)

            for fila in reader:
                # Por defecto DictReader lee todos los valores como strings.
                # Convertimos poblacion y superficie a int para poder operar
                # numéricamente (comparar, ordenar, calcular promedios, etc).
                # strip() elimina espacios en blanco al inicio y al final del string.
                paises.append({
                    "nombre": fila["nombre"].strip(),
                    "poblacion": int(fila["poblacion"]),
                    "superficie": int(fila["superficie"]),
                    "continente": fila["continente"].strip()
                })

    except FileNotFoundError:
        # Error específico cuando el archivo CSV no existe en la ruta indicada
        print("El archivo no existe.")
    except Exception as e:
        # Captura cualquier otro error inesperado (formato incorrecto, permisos, etc.)
        print(f"No se pudo leer el archivo: {e}")

    # Retorna la lista con todos los países cargados.
    # Si hubo un error, retorna la lista vacía.
    return paises

# Esta funcion sirve para actualizar el archivo csv cada vez que el usuario aplique un cambio.
def guardar_paises(paises):
  try:
      with open(ARCHIVO_CSV, "w", newline='', encoding='utf-8') as f:
          writer = csv.DictWriter(f, fieldnames=CAMPOS)
          writer.writeheader()
          writer.writerows(paises)
  except Exception as e:
      print(f"[ERROR] No se pudo guardar el archivo: {e}")

# funcion auxiliar para verificar si existe un pais en el archivo
def existe_pais(paises, nombre):
    for pais in paises:
        if pais["nombre"].strip().lower() == nombre.strip().lower():
            return True
    return False

# funcion para que el usuario agregue paises
def agregar_paises(paises):
  print("---- Nuevo país ----")
  try:  # entradas solicitadas al usuario
        nombre = input("Nombre del nuevo país: ").strip()
        if nombre == "":
            raise ValueError("El nombre del pais no puede ser vacío.")
        if existe_pais(paises, nombre):
            raise ValueError(f"El pais '{nombre}' ya esta cargado en el sistema.")

        poblacion = int(input("Numero de población: "))
        if poblacion <= 0:
            raise ValueError("El numero de poblacion no puede ser menor a 0.")

        superficie = int(input("Superificie km²: "))
        if superficie <=0:
            raise ValueError("La superficie no puede ser menor a 0.")

        continente = input(f"Continente al que pertenece {nombre}: ").strip()
        # Valida que el continente ingresado exista en CONTINENTES.
        # Compara en minúsculas para ignorar mayúsculas/minúsculas.
        while continente.lower() not in [c.lower() for c in CONTINENTES]:
            print(f"Continente inválido. Los válidos son: {', '.join(CONTINENTES)}")
            continente = input("Ingresá nuevamente el continente: ").strip()

        # Recupera el valor oficial de la lista CONTINENTES.
        # Garantiza que se guarde con la escritura correcta (tildes y mayúsculas).
        # Ejemplo: "america" → "América", "europa" → "Europa"
        continente = next(c for c in CONTINENTES if c.lower() == continente.lower())

        # Agrega el nuevo país a la lista como un diccionario con sus cuatro campos
        paises.append({"nombre": nombre, "poblacion": poblacion, "superficie": superficie, "continente": continente})

        # Persiste los cambios escribiendo la lista actualizada en el archivo CSV
        guardar_paises(paises)
        print(f"'{nombre}' agregado correctamente.")

  except ValueError as e:
        print(f"Error: {e} Volviendo al menú.")

# funcion auxiliar para actualizar_datos
def aux_buscar_exacto(paises, nombre):
    for pais in paises:
        if pais["nombre"].strip().lower() == nombre.strip().lower():
            return pais
    return None

# Permite al usuario modificar nombre, población, superficie o continente de un país existente
def actualizar_datos(paises):
    print("--- Actualización de Datos ----")

    # Repite la solicitud hasta que el usuario ingrese un nombre no vacío
    busqueda_valida = False
    while not busqueda_valida:
        try:
            busqueda = input("Qué país desea actualizar?: ")
            if busqueda == "":
                raise ValueError("La búsqueda no puede estar vacía.")
            busqueda_valida = True
        except ValueError as e:
            print(f"Error: {e} Intente nuevamente.")

    # Busca el país por coincidencia exacta de nombre
    pais = aux_buscar_exacto(paises, busqueda)

    if pais:
        # Muestra los datos actuales del país antes de modificar
        print(f"País: {pais['nombre']} | Población: {pais['poblacion']} personas | Superficie: {pais['superficie']}km² | Continente: {pais['continente']}")

        # Submenú con los campos disponibles para modificar
        print("\n1. Nombre")
        print("2. Población")
        print("3. Superficie")
        print("4. Continente")
        try:
            dato = int(input("Seleccione el dato a modificar: "))
            if dato not in (1, 2, 3, 4):
                raise ValueError("Opción inválida.")

            if dato == 1:
                nuevo = input("Nuevo nombre: ").strip()
                if nuevo == "":
                    raise ValueError("El nombre no puede estar vacío.")
                # Verifica que no exista otro país con el mismo nombre
                if existe_pais(paises, nuevo):
                    raise ValueError(f"'{nuevo}' ya existe en el sistema.")
                pais["nombre"] = nuevo

            elif dato == 2:
                nuevo = int(input("Nueva población: "))
                if nuevo <= 0:
                    raise ValueError("La población debe ser mayor a 0.")
                pais["poblacion"] = nuevo

            elif dato == 3:
                nuevo = int(input("Nueva superficie km²: "))
                if nuevo <= 0:
                    raise ValueError("La superficie debe ser mayor a 0.")
                pais["superficie"] = nuevo

            elif dato == 4:
                nuevo = input("Nuevo continente: ").strip()
                # Valida que el continente ingresado exista en la lista CONTINENTES
                while nuevo.lower() not in [c.lower() for c in CONTINENTES]:
                    print(f"Continente inválido. Los válidos son: {', '.join(CONTINENTES)}")
                    nuevo = input("Ingresá nuevamente el continente: ").strip()
                # Recupera el valor oficial con tildes y mayúsculas correctas
                nuevo = next(c for c in CONTINENTES if c.lower() == nuevo.lower())
                pais["continente"] = nuevo

            # Como pais es una referencia al diccionario dentro de la lista,
            # cualquier cambio hecho arriba ya modificó la lista paises directamente.
            # Solo resta persistir los cambios en el archivo CSV.
            guardar_paises(paises)
            print(f"Dato actualizado correctamente.")

        except ValueError as e:
            print(f"Error: {e} Volviendo al menú.")
    else:
        print(f"'{busqueda}' no está cargado en el sistema.")

# funcion aux para buscar_pais
def aux_buscar_pais(paises, nombre):
    resultados = []
    for pais in paises:
        if nombre.strip().lower() in pais["nombre"].strip().lower():
            resultados.append(pais)
    return resultados

# funcion buscar pais por nombre
def buscar_pais(paises):
    print("\n---- Busqueda en el sistema ----")
    busqueda_valida = False
    while not busqueda_valida:
        try:
            busqueda = input("Que pais desea buscar?: ")
            if busqueda == "":
                raise ValueError("La busqueda no puede estar vacía.")
            busqueda_valida = True
        except ValueError as e:
            print(f"Error: {e} Intente nuevamente.")

    resultados = aux_buscar_pais(paises, busqueda)
    if resultados:
        print(f"\n{len(resultados)} resultado(s) encontrado(s):")
        for pais in resultados:
            print(f"País: {pais['nombre']} | Población: {pais['poblacion']} personas | Superficie: {pais['superficie']}km² | Continente: {pais['continente']}")
    else:
        print(f"No se encontraron países con '{busqueda}'.")

# ---- modulo de filtros ----
# el usuario puede filtrar segun distintos criterios (continente, rango de poblacion y superficie)

# filtrar por continente
def filtrar_por_continente(paises):
    # Solicita al usuario el continente a filtrar
    continente = input("Ingresá el continente a filtrar: ").strip()

    # Valida que el continente ingresado exista en la lista CONTINENTES.
    # La comparación se hace en minúsculas de ambos lados para ignorar mayúsculas.
    while continente.lower() not in [c.lower() for c in CONTINENTES]:
        print(f"Continente inválido. Los válidos son: {', '.join(CONTINENTES)}")
        continente = input("Ingresá nuevamente el continente: ").strip()

    # Una vez validado, recupera el valor "oficial" de la lista (con tildes y mayúsculas correctas).
    # Ejemplo: si el usuario escribió "america", lo reemplaza por "América".
    continente = next(c for c in CONTINENTES if c.lower() == continente.lower())

    # Filtra la lista de paises quedándose solo con los que pertenecen al continente elegido.
    # Usa una lista por comprensión para recorrer y evaluar cada país en una sola línea.
    resultados = [p for p in paises if p["continente"] == continente]

    if resultados:
        # Ordena los resultados alfabéticamente por nombre
        # El parámetro key indica el criterio de ordenamiento (nombre en minúsculas).
        resultados.sort(key=lambda p: p["nombre"].lower())

        print(f"\n{len(resultados)} país/es encontrado/s en {continente}:")
        for pais in resultados:
            print(f"País: {pais['nombre']} | Población: {pais['poblacion']} personas | Superficie: {pais['superficie']}km² | Continente: {pais['continente']}")
    else:
        print(f"No se encontraron países en '{continente}'.")

# filtrar por rango de poblacion
def filtrar_por_poblacion(paises):
    print("Ingresá el rango de población (dejá vacío para omitir un extremo):")
    try:
        # Guarda el input como string para poder verificar si está vacío antes de convertir a int
        minimo_input = input("Población mínima: ").strip()
        maximo_input = input("Población máxima: ").strip()

        # Si el usuario dejó el campo vacío, el extremo queda como None (sin límite).
        # Si ingresó un valor, se convierte a int para poder comparar numéricamente.
        minimo = int(minimo_input) if minimo_input != "" else None
        maximo = int(maximo_input) if maximo_input != "" else None

        # Validaciones: solo se ejecutan si el extremo fue ingresado (no es None)
        if minimo is not None and minimo < 0:
            raise ValueError("El mínimo no puede ser negativo.")
        if maximo is not None and maximo < 0:
            raise ValueError("El máximo no puede ser negativo.")
        # Solo tiene sentido comparar mínimo y máximo si ambos fueron ingresados
        if minimo is not None and maximo is not None and minimo > maximo:
            raise ValueError("El mínimo no puede ser mayor al máximo.")

        resultados = []
        for p in paises:
            # Si se definió un mínimo y el país no lo alcanza, se saltea con continue
            if minimo is not None and p["poblacion"] < minimo:
                continue
            # Si se definió un máximo y el país lo supera, se saltea con continue
            if maximo is not None and p["poblacion"] > maximo:
                continue
            # Si pasó ambas condiciones, se agrega a los resultados
            resultados.append(p)

        if resultados:
            # Ordena los resultados de mayor a menor población
            resultados.sort(key=lambda p: p["poblacion"], reverse=True)
            print(f"\n{len(resultados)} país/es encontrado/s:")
            for pais in resultados:
                print(f"País: {pais['nombre']} | Población: {pais['poblacion']} personas | Superficie: {pais['superficie']}km² | Continente: {pais['continente']}")
        else:
            print("No se encontraron países en ese rango de población.")

    except ValueError as e:
        print(f"Error: {e} Volviendo al menú.")

# filtrar por rango de superficie
def filtrar_por_superficie(paises):
    print("Ingresá el rango de superficie (dejá vacío para omitir un extremo):")
    try:
        # Guarda el input como string para poder verificar si está vacío antes de convertir a int
        minimo_input = input("Superficie mínima (km²): ").strip()
        maximo_input = input("Superficie máxima (km²): ").strip()

        # Si el usuario dejó el campo vacío, el extremo queda como None (sin límite).
        # Si ingresó un valor, se convierte a int para poder comparar numéricamente.
        minimo = int(minimo_input) if minimo_input != "" else None
        maximo = int(maximo_input) if maximo_input != "" else None

        # Validaciones: solo se ejecutan si el extremo fue ingresado (no es None)
        if minimo is not None and minimo < 0:
            raise ValueError("El mínimo no puede ser negativo.")
        if maximo is not None and maximo < 0:
            raise ValueError("El máximo no puede ser negativo.")
        # Solo tiene sentido comparar mínimo y máximo si ambos fueron ingresados
        if minimo is not None and maximo is not None and minimo > maximo:
            raise ValueError("El mínimo no puede ser mayor al máximo.")

        resultados = []
        for p in paises:
            # Si se definió un mínimo y el país no lo alcanza, se saltea con continue
            if minimo is not None and p["superficie"] < minimo:
                continue
            # Si se definió un máximo y el país lo supera, se saltea con continue
            if maximo is not None and p["superficie"] > maximo:
                continue
            # Si pasó ambas condiciones, se agrega a los resultados
            resultados.append(p)

        if resultados:
            # Ordena los resultados de mayor a menor superficie
            resultados.sort(key=lambda p: p["superficie"], reverse=True)
            print(f"\n{len(resultados)} país/es encontrado/s:")
            for pais in resultados:
                print(f"País: {pais['nombre']} | Población: {pais['poblacion']} personas | Superficie: {pais['superficie']}km² | Continente: {pais['continente']}")
        else:
            print("No se encontraron países en ese rango de superficie.")

    except ValueError as e:
        print(f"Error: {e} Volviendo al menú.")

# submenu para filtros (similiar al menu de opciones)
def menu_filtros(paises):
    print("\n---- Filtrar Países ----")
    print("1. Por continente")
    print("2. Por rango de población")
    print("3. Por rango de superficie")
    print("0. Volver al menú principal")

    opcion = input("Seleccione una opción: ").strip()

    if opcion == "1":
        filtrar_por_continente(paises)
    elif opcion == "2":
        filtrar_por_poblacion(paises)
    elif opcion == "3":
        filtrar_por_superficie(paises)
    elif opcion == "0":
        return
    else:
        print("Opción inválida.")

# ---- modulo de ordenamiento ----
# el usuario puede ordenar los paises segun distintos criterios (nombre, poblacion y superficie)

def ordenar_paises(paises, criterio, ascendente):
    # Ordena la lista según el criterio elegido y la dirección indicada.
    # reverse=False → ascendente, reverse=True → descendente
    if criterio == "nombre":
        # Para nombre se convierte a minúsculas para ignorar mayúsculas al ordenar
        return sorted(paises, key=lambda p: p["nombre"].lower(), reverse=not ascendente)
    elif criterio == "poblacion":
        return sorted(paises, key=lambda p: p["poblacion"], reverse=not ascendente)
    elif criterio == "superficie":
        return sorted(paises, key=lambda p: p["superficie"], reverse=not ascendente)

def menu_ordenar(paises):
    print("\n---- Ordenar Países ----")
    print("1. Por nombre")
    print("2. Por población")
    print("3. Por superficie")
    print("0. Volver al menú principal")

    opcion = input("Seleccione un criterio: ").strip()

    if opcion == "0":
        return
    if opcion not in ("1", "2", "3"):
        print("Opción inválida.")
        return

    # Mapea la opción elegida al nombre del campo correspondiente
    criterios = {"1": "nombre", "2": "poblacion", "3": "superficie"}
    criterio = criterios[opcion]

    # Submenú para elegir la dirección del ordenamiento
    print("\n1. Ascendente")
    print("2. Descendente")
    direccion = input("Seleccione el orden: ").strip()

    if direccion not in ("1", "2"):
        print("Opción inválida.")
        return

    # True si eligió ascendente, False si eligió descendente
    ascendente = direccion == "1"

    resultados = ordenar_paises(paises, criterio, ascendente)

    direccion_texto = "ascendente" if ascendente else "descendente"
    print(f"\nPaíses ordenados por {criterio} ({direccion_texto}):")
    for pais in resultados:
        print(f"País: {pais['nombre']} | Población: {pais['poblacion']} personas | Superficie: {pais['superficie']}km² | Continente: {pais['continente']}")

# ---- modulo estadisticas ----
""" el ususario cuenta con las siguientes opciones:
- pais con menor y mayor poblacion.
- promedio de poblacion.
- promedio de superficie
- pais por continente"""

def mostrar_estadisticas(paises):
    print("\n---- Estadísticas ----")

    # Verifica que haya países cargados antes de operar
    if not paises:
        print("No hay países cargados en el sistema.")
        return

    # --- País con mayor y menor población ---
    # max() y min() recorren la lista y devuelven el diccionario
    # cuyo campo "poblacion" es el mayor/menor respectivamente
    pais_mayor_pob = max(paises, key=lambda p: p["poblacion"])
    pais_menor_pob = min(paises, key=lambda p: p["poblacion"])

    print(f"\nPaís con mayor población: {pais_mayor_pob['nombre']} ({pais_mayor_pob['poblacion']} personas)")
    print(f"País con menor población: {pais_menor_pob['nombre']} ({pais_menor_pob['poblacion']} personas)")

    # --- Promedios ---
    # sum() acumula el valor del campo indicado de todos los países,
    # se divide por la cantidad total para obtener el promedio.
    # int() elimina los decimales del resultado.
    promedio_poblacion = int(sum(p["poblacion"] for p in paises) / len(paises))
    promedio_superficie = int(sum(p["superficie"] for p in paises) / len(paises))

    print(f"\nPromedio de población: {promedio_poblacion} personas")
    print(f"Promedio de superficie: {promedio_superficie} km²")

    # --- Cantidad de países por continente ---
    # Recorre la lista y construye un diccionario donde cada clave es un continente
    # y su valor es la cantidad de países que pertenecen a ese continente.
    conteo_continentes = {}
    for p in paises:
        continente = p["continente"]
        if continente in conteo_continentes:
            # Si el continente ya existe en el diccionario, incrementa el contador
            conteo_continentes[continente] += 1
        else:
            # Si el continente no existe todavía, lo inicializa en 1
            conteo_continentes[continente] = 1

    print("\nCantidad de países por continente:")
    for continente, cantidad in conteo_continentes.items():
        print(f"  {continente}: {cantidad} país/es")

# funcion aux para mostrar el menu de opciones
def mostrar_menu():
  print("\n" + "=" * 50)
  print("  SISTEMA DE GESTIÓN DE PAÍSES")
  print("=" * 50)
  print("1. Ver todos los países")
  print("2. Agregar país")
  print("3. Actualizar país")
  print("4. Buscar país")
  print("5. Filtrar países")
  print("6. Ordenar países")
  print("7. Estadísticas")
  print("0. Salir")
  print("=" * 50)

"""funcion principal """
def main():
  paises = cargar_paises()
  print(f"  {len(paises)} países cargados desde '{ARCHIVO_CSV}'.")

  # Bucle principal: se ejecuta hasta que el usuario ingrese 0
  while True:
    mostrar_menu()
    opcion = input("Seleccione una opción: ").strip()

    if opcion == "1":
      # listar paises
      print("\n  --- TODOS LOS PAÍSES ---")
      for i, pais in enumerate(paises):
        print(f"{i+1}. País: {pais['nombre']} | Población: {pais['poblacion']} personas | Superficie: {pais['superficie']}km²| Continente: {pais['continente']}")

    elif opcion == "2":
      # agregar pais
      agregar_paises(paises)

    elif opcion == "3":
      # actualizar paises
      actualizar_datos(paises)
    elif opcion == "4":
      # buscar pais por nombre
      buscar_pais(paises)
    elif opcion == "5":
      # filtrar paises
      menu_filtros(paises)
    elif opcion == "6":
      # ordenar paises
      menu_ordenar(paises)

    elif opcion == "7":
      # estadisticas
      mostrar_estadisticas(paises)
    elif opcion == "0":
      print("\nCerrando el programa.... Hasta la proxima!")
      break
    else:
          print("Opción inválida. Ingresá un número del 0 al 7.")


if __name__ == "__main__":
    main()

